name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build project with Maven
      run: mvn clean package -DskipTests
      
    - name: push changes to remote
      run: |
        git config user.name "Action GH"
        git config user.email "boot@user.com"
        git add -f webapp/target/*.war
        git commit -m "From Action GH"
        git push
         
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-app:test,${{ secrets.DOCKERHUB_USERNAME }}/maven-app:latest
