name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build project with Maven
      run: mvn clean package -DskipTests
      
    - name: push changes to remote
      run: |
        git config user.name "Action GH"
        git config user.email "boot@user.com"
        git add -f webapp/target/*.war
        git commit -m "From Action GH"
        git push
         
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/maven-app:test,${{ secrets.DOCKERHUB_USERNAME }}/maven-app:latest



    - name: Deploy in EC2
      env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
      run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            # Now we have got the access of EC2 and we will start the deploy .
            docker stop web1 && docker rm web1
            docker run -d -it -p 80:8080 --name web1 zatorexzo/maven-app
          '
